# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: backup.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='backup.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0c\x62\x61\x63kup.proto\"\xdb\x01\n\x0cSqlStatement\x12\x11\n\tstatement\x18\x01 \x01(\t\x12.\n\nparameters\x18\x02 \x03(\x0b\x32\x1a.SqlStatement.SqlParameter\x1a\x87\x01\n\x0cSqlParameter\x12\x16\n\x0estringParamter\x18\x01 \x01(\t\x12\x18\n\x10integerParameter\x18\x02 \x01(\x04\x12\x17\n\x0f\x64oubleParameter\x18\x03 \x01(\x01\x12\x15\n\rblobParameter\x18\x04 \x01(\x0c\x12\x15\n\rnullparameter\x18\x05 \x01(\x08\"<\n\x10SharedPreference\x12\x0c\n\x04\x66ile\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\"A\n\nAttachment\x12\r\n\x05rowId\x18\x01 \x01(\x04\x12\x14\n\x0c\x61ttachmentId\x18\x02 \x01(\x04\x12\x0e\n\x06length\x18\x03 \x01(\r\"&\n\x06\x41vatar\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06length\x18\x02 \x01(\r\"\"\n\x0f\x44\x61tabaseVersion\x12\x0f\n\x07version\x18\x01 \x01(\r\"\"\n\x06Header\x12\n\n\x02iv\x18\x01 \x01(\x0c\x12\x0c\n\x04salt\x18\x02 \x01(\x0c\"\xd9\x01\n\x0b\x42\x61\x63kupFrame\x12\x17\n\x06header\x18\x01 \x01(\x0b\x32\x07.Header\x12 \n\tstatement\x18\x02 \x01(\x0b\x32\r.SqlStatement\x12%\n\npreference\x18\x03 \x01(\x0b\x32\x11.SharedPreference\x12\x1f\n\nattachment\x18\x04 \x01(\x0b\x32\x0b.Attachment\x12!\n\x07version\x18\x05 \x01(\x0b\x32\x10.DatabaseVersion\x12\x0b\n\x03\x65nd\x18\x06 \x01(\x08\x12\x17\n\x06\x61vatar\x18\x07 \x01(\x0b\x32\x07.Avatar')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SQLSTATEMENT_SQLPARAMETER = _descriptor.Descriptor(
  name='SqlParameter',
  full_name='SqlStatement.SqlParameter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stringParamter', full_name='SqlStatement.SqlParameter.stringParamter', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='integerParameter', full_name='SqlStatement.SqlParameter.integerParameter', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='doubleParameter', full_name='SqlStatement.SqlParameter.doubleParameter', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='blobParameter', full_name='SqlStatement.SqlParameter.blobParameter', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nullparameter', full_name='SqlStatement.SqlParameter.nullparameter', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=236,
)

_SQLSTATEMENT = _descriptor.Descriptor(
  name='SqlStatement',
  full_name='SqlStatement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='statement', full_name='SqlStatement.statement', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='parameters', full_name='SqlStatement.parameters', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_SQLSTATEMENT_SQLPARAMETER, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=236,
)


_SHAREDPREFERENCE = _descriptor.Descriptor(
  name='SharedPreference',
  full_name='SharedPreference',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='file', full_name='SharedPreference.file', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='key', full_name='SharedPreference.key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='SharedPreference.value', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=238,
  serialized_end=298,
)


_ATTACHMENT = _descriptor.Descriptor(
  name='Attachment',
  full_name='Attachment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rowId', full_name='Attachment.rowId', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attachmentId', full_name='Attachment.attachmentId', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='length', full_name='Attachment.length', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=300,
  serialized_end=365,
)


_AVATAR = _descriptor.Descriptor(
  name='Avatar',
  full_name='Avatar',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Avatar.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='length', full_name='Avatar.length', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=367,
  serialized_end=405,
)


_DATABASEVERSION = _descriptor.Descriptor(
  name='DatabaseVersion',
  full_name='DatabaseVersion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='DatabaseVersion.version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=407,
  serialized_end=441,
)


_HEADER = _descriptor.Descriptor(
  name='Header',
  full_name='Header',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='iv', full_name='Header.iv', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='salt', full_name='Header.salt', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=443,
  serialized_end=477,
)


_BACKUPFRAME = _descriptor.Descriptor(
  name='BackupFrame',
  full_name='BackupFrame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='BackupFrame.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='statement', full_name='BackupFrame.statement', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='preference', full_name='BackupFrame.preference', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attachment', full_name='BackupFrame.attachment', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='version', full_name='BackupFrame.version', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end', full_name='BackupFrame.end', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='avatar', full_name='BackupFrame.avatar', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=480,
  serialized_end=697,
)

_SQLSTATEMENT_SQLPARAMETER.containing_type = _SQLSTATEMENT
_SQLSTATEMENT.fields_by_name['parameters'].message_type = _SQLSTATEMENT_SQLPARAMETER
_BACKUPFRAME.fields_by_name['header'].message_type = _HEADER
_BACKUPFRAME.fields_by_name['statement'].message_type = _SQLSTATEMENT
_BACKUPFRAME.fields_by_name['preference'].message_type = _SHAREDPREFERENCE
_BACKUPFRAME.fields_by_name['attachment'].message_type = _ATTACHMENT
_BACKUPFRAME.fields_by_name['version'].message_type = _DATABASEVERSION
_BACKUPFRAME.fields_by_name['avatar'].message_type = _AVATAR
DESCRIPTOR.message_types_by_name['SqlStatement'] = _SQLSTATEMENT
DESCRIPTOR.message_types_by_name['SharedPreference'] = _SHAREDPREFERENCE
DESCRIPTOR.message_types_by_name['Attachment'] = _ATTACHMENT
DESCRIPTOR.message_types_by_name['Avatar'] = _AVATAR
DESCRIPTOR.message_types_by_name['DatabaseVersion'] = _DATABASEVERSION
DESCRIPTOR.message_types_by_name['Header'] = _HEADER
DESCRIPTOR.message_types_by_name['BackupFrame'] = _BACKUPFRAME

SqlStatement = _reflection.GeneratedProtocolMessageType('SqlStatement', (_message.Message,), dict(

  SqlParameter = _reflection.GeneratedProtocolMessageType('SqlParameter', (_message.Message,), dict(
    DESCRIPTOR = _SQLSTATEMENT_SQLPARAMETER,
    __module__ = 'backup_pb2'
    # @@protoc_insertion_point(class_scope:SqlStatement.SqlParameter)
    ))
  ,
  DESCRIPTOR = _SQLSTATEMENT,
  __module__ = 'backup_pb2'
  # @@protoc_insertion_point(class_scope:SqlStatement)
  ))
_sym_db.RegisterMessage(SqlStatement)
_sym_db.RegisterMessage(SqlStatement.SqlParameter)

SharedPreference = _reflection.GeneratedProtocolMessageType('SharedPreference', (_message.Message,), dict(
  DESCRIPTOR = _SHAREDPREFERENCE,
  __module__ = 'backup_pb2'
  # @@protoc_insertion_point(class_scope:SharedPreference)
  ))
_sym_db.RegisterMessage(SharedPreference)

Attachment = _reflection.GeneratedProtocolMessageType('Attachment', (_message.Message,), dict(
  DESCRIPTOR = _ATTACHMENT,
  __module__ = 'backup_pb2'
  # @@protoc_insertion_point(class_scope:Attachment)
  ))
_sym_db.RegisterMessage(Attachment)

Avatar = _reflection.GeneratedProtocolMessageType('Avatar', (_message.Message,), dict(
  DESCRIPTOR = _AVATAR,
  __module__ = 'backup_pb2'
  # @@protoc_insertion_point(class_scope:Avatar)
  ))
_sym_db.RegisterMessage(Avatar)

DatabaseVersion = _reflection.GeneratedProtocolMessageType('DatabaseVersion', (_message.Message,), dict(
  DESCRIPTOR = _DATABASEVERSION,
  __module__ = 'backup_pb2'
  # @@protoc_insertion_point(class_scope:DatabaseVersion)
  ))
_sym_db.RegisterMessage(DatabaseVersion)

Header = _reflection.GeneratedProtocolMessageType('Header', (_message.Message,), dict(
  DESCRIPTOR = _HEADER,
  __module__ = 'backup_pb2'
  # @@protoc_insertion_point(class_scope:Header)
  ))
_sym_db.RegisterMessage(Header)

BackupFrame = _reflection.GeneratedProtocolMessageType('BackupFrame', (_message.Message,), dict(
  DESCRIPTOR = _BACKUPFRAME,
  __module__ = 'backup_pb2'
  # @@protoc_insertion_point(class_scope:BackupFrame)
  ))
_sym_db.RegisterMessage(BackupFrame)


# @@protoc_insertion_point(module_scope)
